// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebQLLuongNV.Models;

#nullable disable

namespace WebQLLuongNV.Migrations
{
    [DbContext(typeof(QlnvpartTimeContext))]
    [Migration("20241119155126_AddMaLoaiCongViecToChiTietLichLam")]
    partial class AddMaLoaiCongViecToChiTietLichLam
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VaiTroPhanQuyen", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .HasColumnType("int");

                    b.Property<int>("MaQuyen")
                        .HasColumnType("int");

                    b.HasKey("MaVaiTro", "MaQuyen")
                        .HasName("PK__VaiTro_P__9398F622688720E1");

                    b.HasIndex("MaQuyen");

                    b.ToTable("VaiTro_PhanQuyen", (string)null);
                });

            modelBuilder.Entity("WebQLLuongNV.Models.BangLuongNv", b =>
                {
                    b.Property<string>("MaLuong")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaNhanVien")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaQuanLy")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("ThangNam")
                        .HasColumnType("date");

                    b.Property<decimal?>("TongLuong")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("MaLuong")
                        .HasName("PK__BangLuon__6609A48D7B920F62");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("BangLuongNV", (string)null);
                });

            modelBuilder.Entity("WebQLLuongNV.Models.CalamViec", b =>
                {
                    b.Property<int>("IdcalamViec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDCalamViec");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdcalamViec"));

                    b.Property<string>("TenCa")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<TimeSpan?>("ThoiGian")
                        .HasColumnType("time");

                    b.HasKey("IdcalamViec")
                        .HasName("PK__CalamVie__CD76E12AB99D378A");

                    b.ToTable("CalamViec", (string)null);
                });

            modelBuilder.Entity("WebQLLuongNV.Models.ChiTietLichLam", b =>
                {
                    b.Property<int>("IdChitietLichLam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdChitietLichLam"));

                    b.Property<TimeSpan?>("GioBd")
                        .HasColumnType("time")
                        .HasColumnName("GioBD");

                    b.Property<TimeSpan?>("GioKt")
                        .HasColumnType("time")
                        .HasColumnName("GioKT");

                    b.Property<int?>("IdcaLamViec")
                        .HasColumnType("int")
                        .HasColumnName("IDCaLamViec");

                    b.Property<decimal?>("LuongLoaiCv")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("LuongLoaiCV");

                    b.Property<string>("MaLichLam")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaLoaiCongViec")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("NoiLam")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SonguoiLam")
                        .HasColumnType("int");

                    b.Property<int?>("TongSoCaQuyDinh")
                        .HasColumnType("int");

                    b.HasKey("IdChitietLichLam")
                        .HasName("PK__ChiTietL__C96CD8A8D5A0C0E1");

                    b.HasIndex("IdcaLamViec");

                    b.HasIndex("MaLichLam");

                    b.HasIndex("MaLoaiCongViec");

                    b.ToTable("ChiTietLichLam", (string)null);
                });

            modelBuilder.Entity("WebQLLuongNV.Models.DangKy", b =>
                {
                    b.Property<string>("MaLichLam")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaNhanVien")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<bool?>("HoanThanh")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ThoiGianDky")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ThoiGianDKY")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("MaLichLam", "MaNhanVien")
                        .HasName("PK__DangKy__6D042AEE43103482");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("DangKy", (string)null);
                });

            modelBuilder.Entity("WebQLLuongNV.Models.LichLam", b =>
                {
                    b.Property<string>("MaLichLam")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaLoaiCongViec")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaQuanLy")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("SoCaQuyDinh")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThuNgayThangNam")
                        .HasColumnType("date");

                    b.HasKey("MaLichLam")
                        .HasName("PK__LichLam__0A7F064A8D9ED799");

                    b.HasIndex("MaLoaiCongViec");

                    b.HasIndex("MaQuanLy");

                    b.ToTable("LichLam", (string)null);
                });

            modelBuilder.Entity("WebQLLuongNV.Models.LoaiCongViec", b =>
                {
                    b.Property<string>("MaLoaiCongViec")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("TenLoaiCongViec")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLoaiCongViec")
                        .HasName("PK__LoaiCong__D119044C89DD5F08");

                    b.ToTable("LoaiCongViec", (string)null);
                });

            modelBuilder.Entity("WebQLLuongNV.Models.NhanVien", b =>
                {
                    b.Property<string>("MaNhanVien")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Cmnd")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("CMND");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MaTaiKhoan")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("SDT");

                    b.Property<string>("TenNhanVien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("MaNhanVien")
                        .HasName("PK__NhanVien__77B2CA47B3F5BFBB");

                    b.HasIndex("MaTaiKhoan");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("WebQLLuongNV.Models.PhanQuyen", b =>
                {
                    b.Property<int>("MaQuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaQuyen"));

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("MaQuyen")
                        .HasName("PK__PhanQuye__1D4B7ED41B1B3FA5");

                    b.HasIndex(new[] { "TenQuyen" }, "UQ__PhanQuye__5637EE7975F67A45")
                        .IsUnique();

                    b.ToTable("PhanQuyen", (string)null);
                });

            modelBuilder.Entity("WebQLLuongNV.Models.TaiKhoan", b =>
                {
                    b.Property<string>("MaTaiKhoan")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("MaVaiTro")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TenTaiKhoan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValueSql("('Active')");

                    b.HasKey("MaTaiKhoan")
                        .HasName("PK__TaiKhoan__AD7C6529A731C6D9");

                    b.HasIndex("MaVaiTro");

                    b.HasIndex(new[] { "TenTaiKhoan" }, "UQ__TaiKhoan__B106EAF831AA2447")
                        .IsUnique();

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("WebQLLuongNV.Models.TongLuongAllnv", b =>
                {
                    b.Property<DateTime>("ThangID")
                        .HasColumnType("date")
                        .HasColumnName("Thang_iD");

                    b.Property<string>("MaLuong")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaQuanLy")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal?>("TongLuongAllNv1")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("TongLuongAllNV");

                    b.HasKey("ThangID")
                        .HasName("PK__TongLuon__D122B1991FA36065");

                    b.HasIndex("MaLuong");

                    b.HasIndex("MaQuanLy");

                    b.ToTable("TongLuongALLNV", (string)null);
                });

            modelBuilder.Entity("WebQLLuongNV.Models.VaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVaiTro"));

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaVaiTro")
                        .HasName("PK__VaiTro__C24C41CF4D1B41C0");

                    b.HasIndex(new[] { "TenVaiTro" }, "UQ__VaiTro__1DA55814EC57616D")
                        .IsUnique();

                    b.ToTable("VaiTro", (string)null);
                });

            modelBuilder.Entity("VaiTroPhanQuyen", b =>
                {
                    b.HasOne("WebQLLuongNV.Models.PhanQuyen", null)
                        .WithMany()
                        .HasForeignKey("MaQuyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__VaiTro_Ph__MaQuy__3E52440B");

                    b.HasOne("WebQLLuongNV.Models.VaiTro", null)
                        .WithMany()
                        .HasForeignKey("MaVaiTro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__VaiTro_Ph__MaVai__3D5E1FD2");
                });

            modelBuilder.Entity("WebQLLuongNV.Models.BangLuongNv", b =>
                {
                    b.HasOne("WebQLLuongNV.Models.NhanVien", "MaNhanVienNavigation")
                        .WithMany("BangLuongNvs")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__BangLuong__MaNha__59FA5E80");

                    b.Navigation("MaNhanVienNavigation");
                });

            modelBuilder.Entity("WebQLLuongNV.Models.ChiTietLichLam", b =>
                {
                    b.HasOne("WebQLLuongNV.Models.CalamViec", "IdcaLamViecNavigation")
                        .WithMany("ChiTietLichLams")
                        .HasForeignKey("IdcaLamViec")
                        .HasConstraintName("FK__ChiTietLi__IDCaL__06CD04F7");

                    b.HasOne("WebQLLuongNV.Models.LichLam", "MaLichLamNavigation")
                        .WithMany("ChiTietLichLams")
                        .HasForeignKey("MaLichLam")
                        .HasConstraintName("FK__ChiTietLi__MaLic__05D8E0BE");

                    b.HasOne("WebQLLuongNV.Models.LoaiCongViec", "MaLoaiCongViecNavigation")
                        .WithMany("ChiTietLichLams")
                        .HasForeignKey("MaLoaiCongViec")
                        .HasConstraintName("FK_ChiTietLichLam_LoaiCongViec");

                    b.Navigation("IdcaLamViecNavigation");

                    b.Navigation("MaLichLamNavigation");

                    b.Navigation("MaLoaiCongViecNavigation");
                });

            modelBuilder.Entity("WebQLLuongNV.Models.DangKy", b =>
                {
                    b.HasOne("WebQLLuongNV.Models.LichLam", "MaLichLamNavigation")
                        .WithMany("DangKies")
                        .HasForeignKey("MaLichLam")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__DangKy__MaLichLa__5629CD9C");

                    b.HasOne("WebQLLuongNV.Models.NhanVien", "MaNhanVienNavigation")
                        .WithMany("DangKies")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__DangKy__MaNhanVi__571DF1D5");

                    b.Navigation("MaLichLamNavigation");

                    b.Navigation("MaNhanVienNavigation");
                });

            modelBuilder.Entity("WebQLLuongNV.Models.LichLam", b =>
                {
                    b.HasOne("WebQLLuongNV.Models.LoaiCongViec", "MaLoaiCongViecNavigation")
                        .WithMany("LichLams")
                        .HasForeignKey("MaLoaiCongViec")
                        .HasConstraintName("FK_LichLam_LoaiCongViec");

                    b.HasOne("WebQLLuongNV.Models.NhanVien", "MaQuanLyNavigation")
                        .WithMany("LichLams")
                        .HasForeignKey("MaQuanLy")
                        .HasConstraintName("FK__LichLam__MaQuanL__4BAC3F29");

                    b.Navigation("MaLoaiCongViecNavigation");

                    b.Navigation("MaQuanLyNavigation");
                });

            modelBuilder.Entity("WebQLLuongNV.Models.NhanVien", b =>
                {
                    b.HasOne("WebQLLuongNV.Models.TaiKhoan", "MaTaiKhoanNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__NhanVien__MaTaiK__46E78A0C");

                    b.Navigation("MaTaiKhoanNavigation");
                });

            modelBuilder.Entity("WebQLLuongNV.Models.TaiKhoan", b =>
                {
                    b.HasOne("WebQLLuongNV.Models.VaiTro", "MaVaiTroNavigation")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("MaVaiTro")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__TaiKhoan__MaVaiT__440B1D61");

                    b.Navigation("MaVaiTroNavigation");
                });

            modelBuilder.Entity("WebQLLuongNV.Models.TongLuongAllnv", b =>
                {
                    b.HasOne("WebQLLuongNV.Models.BangLuongNv", "MaLuongNavigation")
                        .WithMany("TongLuongAllnvs")
                        .HasForeignKey("MaLuong")
                        .HasConstraintName("FK_TongLuongALLNV_BangLuongNV");

                    b.HasOne("WebQLLuongNV.Models.NhanVien", "MaQuanLyNavigation")
                        .WithMany("TongLuongAllnvs")
                        .HasForeignKey("MaQuanLy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_TongLuongALLNV_NhanVien");

                    b.Navigation("MaLuongNavigation");

                    b.Navigation("MaQuanLyNavigation");
                });

            modelBuilder.Entity("WebQLLuongNV.Models.BangLuongNv", b =>
                {
                    b.Navigation("TongLuongAllnvs");
                });

            modelBuilder.Entity("WebQLLuongNV.Models.CalamViec", b =>
                {
                    b.Navigation("ChiTietLichLams");
                });

            modelBuilder.Entity("WebQLLuongNV.Models.LichLam", b =>
                {
                    b.Navigation("ChiTietLichLams");

                    b.Navigation("DangKies");
                });

            modelBuilder.Entity("WebQLLuongNV.Models.LoaiCongViec", b =>
                {
                    b.Navigation("ChiTietLichLams");

                    b.Navigation("LichLams");
                });

            modelBuilder.Entity("WebQLLuongNV.Models.NhanVien", b =>
                {
                    b.Navigation("BangLuongNvs");

                    b.Navigation("DangKies");

                    b.Navigation("LichLams");

                    b.Navigation("TongLuongAllnvs");
                });

            modelBuilder.Entity("WebQLLuongNV.Models.TaiKhoan", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("WebQLLuongNV.Models.VaiTro", b =>
                {
                    b.Navigation("TaiKhoans");
                });
#pragma warning restore 612, 618
        }
    }
}
